os: osx
osx_image: xcode11

language: node_js
node_js: 10

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - yarn lint:js --max-warnings=0
  - yarn lint:css
  - yarn test
  - yarn build
