jobs: 
  - job: LintAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: CacheBeta@0
        inputs:
          key: |
            $(Agent.OS)
            $(Build.SourcesDirectory)/yarn.lock
          path: $(Pipeline.Workspace)/.cache/yarn

      - task: UseNode@1
        inputs:
            version: "10"
        displayName: "[Client] Install NodeJS"

      - script: |
            yarn
        condition: ne(variables['CacheRestored'], 'true')
        displayName: "[Client] Run `yarn install`"

      - script: |
            yarn lint:js --max-warnings=0
            yarn lint:css
            yarn test
            yarn build
        displayName: "[Client] Run `yarn` lint and build"
