jobs: 
  - job: LintAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseNode@1
        inputs:
          version: '10'
          checkLatest: true
        displayName: "Install NodeJS"
      
      - task: CacheBeta@0
        inputs:
          key: |
            $(Agent.OS)
            $(Build.SourcesDirectory)/yarn.lock
          path: $(Pipeline.Workspace)/.cache/yarn

      - script: |
            yarn
        condition: ne(variables['CacheRestored'], 'true')
        displayName: "Run `yarn install`"

      - script: |
            yarn lint:js --max-warnings=0
            yarn lint:css
            yarn test
            yarn build
        displayName: "Run `yarn` lint and build"
